import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  wrap: {
    display: "flex",
    justifyContent: "center",
    paddingTop: 24,
    paddingBottom: 24,
  },
  card: {
    width: "100%",
    maxWidth: 520,
    background: "white",
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 8px 30px rgba(0,0,0,0.08)",
    border: "1px solid rgba(0,0,0,0.06)",
  },
  title: { margin: 0, fontSize: 22, fontWeight: 700 },
  subtitle: { marginTop: 8, marginBottom: 20, color: "#555", lineHeight: 1.4 },
  label: { display: "block", marginBottom: 6, fontWeight: 600 },
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid #ddd",
    outline: "none",
    fontSize: 15,
  },
  row: { marginBottom: 14 },
  button: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    border: "none",
    cursor: "pointer",
    fontSize: 15,
    fontWeight: 700,
    background: "#111",
    color: "white",
  },
  note: { marginTop: 12, fontSize: 13, color: "#666", lineHeight: 1.4 },
  msgError: {
    marginTop: 12,
    padding: 10,
    borderRadius: 10,
    background: "#ffecec",
    color: "#8a1f1f",
    border: "1px solid #ffd2d2",
  },
  msgSuccess: {
    marginTop: 12,
    padding: 10,
    borderRadius: 10,
    background: "#ecfff1",
    color: "#145a2a",
    border: "1px solid #c9f2d2",
  },
};
